sonar.projectKey=evelynhuang0403_COMP313_DesigantedDrivingApp_Devops
sonar.projectName=COMP313_DesigantedDrivingApp_Devops
sonar.organization=evelynhuang0403

# Source directories
sonar.sources=DesignatedDrivingAPI/src,DesignatedDrivingClient/src

# Test directories
sonar.tests=DesignatedDrivingAPI/src/tests

# Language
sonar.language=js
sonar.javascript.lcov.reportPaths=DesignatedDrivingAPI/coverage/lcov.info

# SonarCloud host
sonar.host.url=https://sonarcloud.io

# Exclusions
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/*.test.js
sonar.coverage.exclusions=**/*.test.js,**/node_modules/**
